compiler:
  build: "."
  volumes:
   - ./volume:/app/
  tty: true
  environment:
    - EDITOR=vim
  command: pandoc -F pandoc-crossref /app/report.md -o /app/report.pdf --pdf-engine lualatex -V luatexjapresetoptions=ipa -N
